= CUI JWT Quarkus Integration
:toc: macro
:toclevels: 3
:toc-title: Table of Contents
:icons: font

A Quarkus extension for the CUI JWT validation library.

toc::[]

== Overview

This module provides integration of the CUI JWT validation library into Quarkus applications. It includes:

* Quarkus configuration support
* CDI producers for JWT validation components
* Integrated security checks
* Support for multiple JWT issuers

== Documentation

=== Configuration Documentation

The complete documentation of the configuration options can be found in the Quarkus extension metadata:

link:cui-jwt-quarkus/src/main/resources/META-INF/quarkus-config-doc.adoc[Quarkus Configuration Documentation]

=== CDI Beans and Injection

The extension provides the following CDI beans:

==== TokenValidator

The `TokenValidator` is provided as an ApplicationScoped bean and can be directly injected into your application:

[source,java]
----
@Inject
TokenValidator tokenValidator;
----

The TokenValidator is automatically initialized with the configuration settings from the Quarkus configuration.

Example usage:

[source,java]
----
@ApplicationScoped
public class JwtAuthenticationService {

    @Inject
    TokenValidator tokenValidator;

    public Optional<AccessTokenContent> validateAccessToken(String token) {
        try {
            return tokenValidator.validateAccessToken(token);
        } catch (TokenValidationException e) {
            // Handle validation exception
            return Optional.empty();
        }
    }
}
----

=== Test Setup

Information on setting up tests can be found here:

link:doc/quarkus-test-setup.adoc[Quarkus Test Setup]

=== Native Image Support

The extension supports GraalVM Native Image compilation. More information can be found here:

link:doc/native-image-support.adoc[Native Image Support]

== Modules

The project consists of the following modules:

* `deployment` - Contains the Quarkus deployment code for the extension
* `runtime` - Contains the runtime code for the extension
* `doc` - Contains additional documentation

== Development

Development information can be found in the `todo` directory, which contains tasks and notes for further development.
